# Generated by Django 5.0.6 on 2024-08-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
