# Generated by Django 5.0.6 on 2024-08-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_mall', '0002_alter_products_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
    ]
