# Generated by Django 5.0.6 on 2024-09-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_mall', '0003_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='international',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
