# Generated by Django 5.0.6 on 2024-09-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_mall', '0005_alter_products_international'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='international',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
