# Generated by Django 5.0.6 on 2024-09-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_mall', '0006_alter_products_international'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image10',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image5',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image6',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image7',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image8',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image9',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/products/'),
        ),
    ]
