# Generated by Django 5.0.6 on 2025-08-25 13:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_mall', '0007_products_image10_products_image4_products_image5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
