# Generated by Django 5.0.6 on 2025-08-25 16:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_mall', '0009_alter_products_image1_alter_products_image10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=cloudinary.models.CloudinaryField(default='uploads/products/logo.png', max_length=255, verbose_name='image'),
        ),
    ]
