# Generated by Django 5.0.6 on 2025-08-25 17:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_mall', '0010_alter_products_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/diovsna1y/image/upload/v1756129362/logo_bgsqwu.png', max_length=255, verbose_name='image'),
        ),
    ]
